name: NxColor CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    name: "Format check and tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25.0'
          elixir-version: '1.13'
      - name: Install mix dependencies
        run: mix deps.get
      - name: Check formatting
        run: mix format --check-formatted
      - name: Run tests
        run: MIX_ENV=test mix do compile --warnings-as-errors, test
  exla_test:
    name: "Tests using EXLA"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25.0'
          elixir-version: '1.13'
      - name: Install mix dependencies
        run: mix deps.get
      - name: Run tests against EXLA
        run: MIX_ENV=test USE_EXLA=true mix do compile --warnings-as-errors, test
